import InputForm from "@/components/InputForm";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Separator } from "@/components/ui/separator";

const page = () => {
  return (
    <main className="w-full mb-6">
      <h1 className="font-extrabold text-2xl md:text-4xl pt-2">
        Generate Your AI Image
      </h1>
      <p className="pt-2 font-m">
        Create through a collection of imaginative and visually stunning images
        generated by DALL-E AI and share them with the Community
      </p>
      <Alert variant={"destructive"} className="my-6 dark:text-red-600">
        <AlertTitle>API Limit Exhausted</AlertTitle>
        <AlertDescription>Images temporarily unavailable due to OpenAI API limits. Apologies! Enjoy a random stock image as an output.</AlertDescription>
      </Alert>
      <Separator className="my-4 " />
      <InputForm />
    </main>
  );
};

export default page;
