import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cn("bg-primary-foreground", GeistSans.className)}>
        <main className=" flex flex-col min-h-screen ">
          <Navbar />
          <div className="flex-1 flex max-w-7xl mx-auto w-full px-2.5 xl:px-0 pt-2.5">
            {children}
          </div>
        </main>
        <Toaster />
      </body>
    </html>
  );
}
