import PhotoGallery from "@/components/PhotoGallery";
import { Separator } from "@/components/ui/separator";

export default function Home() {
  return (
    <div className="w-full pt-4  ">
      <h1 className="font-extrabold text-2xl md:text-4xl pt-2 ">
        The Community Showcase
      </h1>
      <p className="pt-2 font-m">
        Browse through a collection of imaginative and visually stunning images
        generated by DALL-E AI
      </p>
      <Separator className="my-4 bg-muted-foreground" />
      <PhotoGallery />
    </div>
  );
}
